//! Capability **sets** and compile-time membership.
//!
//! # The problem
//!
//! `Client<C>`'s guarantee is that an accessor for a capability exists **only**
//! when that capability is in `C`. `Client<(Permission,)>::fs_read(..)` must be
//! a compile error, not a runtime `None`.
//!
//! The obvious encoding does not work. Writing
//!
//! ```text
//! impl<A, B> Has<A> for (A, B) {}
//! impl<A, B> Has<B> for (A, B) {}
//! ```
//!
//! is two impls of the *same* trait for the *same* type `(A, B)` whenever `A`
//! and `B` unify — rustc rejects them as overlapping, and there is no
//! specialization or negative-reasoning escape hatch on stable.
//!
//! # The encoding used here
//!
//! [`Has`] carries a second, *disambiguating* type parameter: the **position**
//! of the marker in the tuple, as a type-level Peano numeral
//! ([`Here`], [`There<Here>`](There), …).
//!
//! ```text
//! impl<A, B> Has<A, Here>        for (A, B) {}
//! impl<A, B> Has<B, There<Here>> for (A, B) {}
//! ```
//!
//! These no longer overlap — they are impls of *different* traits
//! (`Has<_, Here>` and `Has<_, There<Here>>`) — so the whole 0..=8 range is
//! expressible with no coherence conflict at all. The accessors are generic
//! over the index and never mention it:
//!
//! ```text
//! pub fn fs_read<I>(&self, ..) -> ..  where C: Has<FsRead, I>
//! ```
//!
//! and rustc infers `I` from whichever impl matches. This is the same
//! index-disambiguated selector `frunk` uses for heterogeneous lists.
//!
//! ## The one honest edge
//!
//! A tuple that lists the same marker twice — `Client<(FsRead, FsRead)>` — has
//! two applicable impls with different indices, so `I` is ambiguous and the
//! call fails to compile with a type-annotation error. A duplicated capability
//! is a malformed declaration, so failing is correct; it is recorded here
//! because the *message* is about inference rather than about duplication.
//!
//! # Derivation
//!
//! [`CapabilitySet`] turns `C` into `Vec<CallbackIr>`. Both it and [`Has`] are
//! sealed (`Has` through its `CapabilitySet` supertrait, `CapabilitySet`
//! through [`sealed::Sealed`](super::markers::sealed::Sealed)), so the only
//! capability sets that exist are tuples of the markers this crate defines.
//! That is what makes the declared set and the usable set the same object.

use std::marker::PhantomData;

use crate::ir::CallbackIr;

use super::markers::{sealed, Capability};

/// Type-level index: position zero.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct Here;

/// Type-level index: one position past `I`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct There<I>(PhantomData<I>);

/// A tuple of [`Capability`] markers, viewed as a set.
///
/// Sealed: implemented for `()` and for 1..=8-tuples of markers, and nothing
/// else. [`callbacks`](Self::callbacks) is the `C -> Vec<CallbackIr>` bridge a
/// later build uses to populate [`crate::ir::MethodIr::callbacks`] straight
/// from a method signature.
pub trait CapabilitySet: sealed::Sealed {
    /// How many capabilities are in the set.
    const ARITY: usize;

    /// The IR descriptors for every capability in the set, in declaration
    /// order. Each comes from that marker's own
    /// [`Capability::descriptor`], so the declaration cannot drift from what
    /// the handle can actually call.
    fn callbacks() -> Vec<CallbackIr>;

    /// Just the wire names, in declaration order.
    fn names() -> Vec<&'static str>;
}

/// `C` contains marker `M` at position `I`.
///
/// Never written by hand: it appears only as a bound on `Client<C>`'s
/// accessors, where `I` is inferred. See the [module docs](self) for why the
/// index parameter is load-bearing.
pub trait Has<M: Capability, I>: CapabilitySet {}

macro_rules! set_impl {
    ( $($name:ident),* ) => {
        impl<$($name: Capability),*> sealed::Sealed for ($($name,)*) {}

        impl<$($name: Capability),*> CapabilitySet for ($($name,)*) {
            const ARITY: usize = <[()]>::len(&[$(set_impl!(@unit $name)),*]);

            fn callbacks() -> Vec<CallbackIr> {
                vec![$($name::descriptor()),*]
            }

            fn names() -> Vec<&'static str> {
                vec![$($name::NAME),*]
            }
        }
    };
    (@unit $name:ident) => { () };
}

macro_rules! has_impl {
    ( ($($all:ident),*), $target:ident, $idx:ty ) => {
        impl<$($all: Capability),*> Has<$target, $idx> for ($($all,)*) {}
    };
}

// --- generated by the `has_impl!` / `set_impl!` macros below ---
set_impl!();
set_impl!(A);
set_impl!(A, B);
set_impl!(A, B, C);
set_impl!(A, B, C, D);
set_impl!(A, B, C, D, E);
set_impl!(A, B, C, D, E, F);
set_impl!(A, B, C, D, E, F, G);
set_impl!(A, B, C, D, E, F, G, H);
has_impl!((A), A, Here);
has_impl!((A, B), A, Here);
has_impl!((A, B), B, There<Here>);
has_impl!((A, B, C), A, Here);
has_impl!((A, B, C), B, There<Here>);
has_impl!((A, B, C), C, There<There<Here>>);
has_impl!((A, B, C, D), A, Here);
has_impl!((A, B, C, D), B, There<Here>);
has_impl!((A, B, C, D), C, There<There<Here>>);
has_impl!((A, B, C, D), D, There<There<There<Here>>>);
has_impl!((A, B, C, D, E), A, Here);
has_impl!((A, B, C, D, E), B, There<Here>);
has_impl!((A, B, C, D, E), C, There<There<Here>>);
has_impl!((A, B, C, D, E), D, There<There<There<Here>>>);
has_impl!((A, B, C, D, E), E, There<There<There<There<Here>>>>);
has_impl!((A, B, C, D, E, F), A, Here);
has_impl!((A, B, C, D, E, F), B, There<Here>);
has_impl!((A, B, C, D, E, F), C, There<There<Here>>);
has_impl!((A, B, C, D, E, F), D, There<There<There<Here>>>);
has_impl!((A, B, C, D, E, F), E, There<There<There<There<Here>>>>);
has_impl!((A, B, C, D, E, F), F, There<There<There<There<There<Here>>>>>);
has_impl!((A, B, C, D, E, F, G), A, Here);
has_impl!((A, B, C, D, E, F, G), B, There<Here>);
has_impl!((A, B, C, D, E, F, G), C, There<There<Here>>);
has_impl!((A, B, C, D, E, F, G), D, There<There<There<Here>>>);
has_impl!((A, B, C, D, E, F, G), E, There<There<There<There<Here>>>>);
has_impl!((A, B, C, D, E, F, G), F, There<There<There<There<There<Here>>>>>);
has_impl!((A, B, C, D, E, F, G), G, There<There<There<There<There<There<Here>>>>>>);
has_impl!((A, B, C, D, E, F, G, H), A, Here);
has_impl!((A, B, C, D, E, F, G, H), B, There<Here>);
has_impl!((A, B, C, D, E, F, G, H), C, There<There<Here>>);
has_impl!((A, B, C, D, E, F, G, H), D, There<There<There<Here>>>);
has_impl!((A, B, C, D, E, F, G, H), E, There<There<There<There<Here>>>>);
has_impl!((A, B, C, D, E, F, G, H), F, There<There<There<There<There<Here>>>>>);
has_impl!((A, B, C, D, E, F, G, H), G, There<There<There<There<There<There<Here>>>>>>);
has_impl!((A, B, C, D, E, F, G, H), H, There<There<There<There<There<There<There<Here>>>>>>>);
